# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GoogleMapsUITests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      BROWSERSTACK_USERNAME: your_username
      BROWSERSTACK_ACCESS_KEY: your_access_key
      EXECUTION_ENVIRONMENT: Local
      BROWSER_NAME: Chrome
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build
    - name: Run Test
      run: dotnet test
